name: SentryGuard
version: '${project.version}'
main: dev.tf2levi.sentryguard.SentryGuard
api-version: 1.19
authors: [ tf2levi, repa12 ]
description: This plugin adds a customizable sentry figure to your server.
website: https://github.com/TryHardDo
commands:
  sentryguard:
    permission-message: "§cYou do not have permission to execute this command!"
    usage: "§cCommand usage tip: §e/<command> [args] §7| §cUse §e/<command> help §cto list the available commands!"
    permission: sguard.default
    description: Used to interact with the plugin.
permissions:
  sguard.default:
    default: true
    description: Permission to use the basic command(s) of the plugin.